import io
import time
import zlib
import logging
from typing import Dict

import torch

logger = logging.getLogger(__name__)

def compress_weights(state_dict: Dict[str, torch.Tensor], use_fp16: bool = True, sparse_threshold: float = 0.001) -> bytes:
    """
    Applies Phase 3 optimizations:
    1. Sparse Updates (pruning small values to zero).
    2. Gradient/Weight Compression (FP32 -> FP16).
    3. Network payload compression via zlib (benefits greatly from sparse zeros).
    """
    optimized_dict = {}
    for k, v in state_dict.items():
        tensor = v.clone()
        
        # 1. Sparsify (Sparse Updates)
        if sparse_threshold > 0.0 and tensor.is_floating_point():
            mask = torch.abs(tensor) > sparse_threshold
            tensor = tensor * mask
            
        # 2. FP16 Quantization (Gradient Compression)
        if use_fp16 and tensor.is_floating_point():
            tensor = tensor.to(torch.float16)
            
        optimized_dict[k] = tensor

    # Save to memory buffer
    buffer = io.BytesIO()
    torch.save(optimized_dict, buffer)
    raw_bytes = buffer.getvalue()
    
    # 3. Zlib compression to transmit sparse data efficiently
    # The zeros generated by sparsification compress extremely well
    zipped_bytes = zlib.compress(raw_bytes, level=6)
    
    return zipped_bytes

def decompress_weights(zipped_bytes: bytes) -> Dict[str, torch.Tensor]:
    """
    Decompresses zlib bytes and upcasts back to FP32 for robust server aggregation.
    """
    raw_bytes = zlib.decompress(zipped_bytes)
    buffer = io.BytesIO(raw_bytes)
    state_dict = torch.load(buffer, weights_only=False, map_location="cpu")
    
    # Restore to FP32 for PyTorch training and aggregation compatibility
    for k, v in state_dict.items():
        if v.dtype == torch.float16:
            state_dict[k] = v.to(torch.float32)
            
    return state_dict
