# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/network/protocol.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/network/protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asrc/network/protocol.proto\x12\tfederated\":\n\x0fRegisterRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0csample_count\x18\x02 \x01(\x05\"K\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rcurrent_round\x18\x03 \x01(\x05\"!\n\x0cModelRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"I\n\rModelResponse\x12\x15\n\rcurrent_round\x18\x01 \x01(\x05\x12\x0f\n\x07weights\x18\x02 \x01(\x0c\x12\x10\n\x08metadata\x18\x03 \x01(\t\"\x8a\x01\n\x12LocalUpdateRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x16\n\x0etraining_round\x18\x02 \x01(\x05\x12\x0f\n\x07weights\x18\x03 \x01(\x0c\x12\x14\n\x0csamples_used\x18\x04 \x01(\x05\x12\x0c\n\x04loss\x18\x05 \x01(\x02\x12\x14\n\x0cmetrics_json\x18\x06 \x01(\t\"8\n\x13LocalUpdateResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf5\x01\n\x11\x46\x65\x64\x65ratedLearning\x12I\n\x0eRegisterClient\x12\x1a.federated.RegisterRequest\x1a\x1b.federated.RegisterResponse\x12\x43\n\x0eGetGlobalModel\x12\x17.federated.ModelRequest\x1a\x18.federated.ModelResponse\x12P\n\x0fSendLocalUpdate\x12\x1d.federated.LocalUpdateRequest\x1a\x1e.federated.LocalUpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.network.protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=41
  _globals['_REGISTERREQUEST']._serialized_end=99
  _globals['_REGISTERRESPONSE']._serialized_start=101
  _globals['_REGISTERRESPONSE']._serialized_end=176
  _globals['_MODELREQUEST']._serialized_start=178
  _globals['_MODELREQUEST']._serialized_end=211
  _globals['_MODELRESPONSE']._serialized_start=213
  _globals['_MODELRESPONSE']._serialized_end=286
  _globals['_LOCALUPDATEREQUEST']._serialized_start=289
  _globals['_LOCALUPDATEREQUEST']._serialized_end=427
  _globals['_LOCALUPDATERESPONSE']._serialized_start=429
  _globals['_LOCALUPDATERESPONSE']._serialized_end=485
  _globals['_FEDERATEDLEARNING']._serialized_start=488
  _globals['_FEDERATEDLEARNING']._serialized_end=733
# @@protoc_insertion_point(module_scope)
